# Generated by Django 5.0.3 on 2024-07-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='history',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='history',
            name='status',
        ),
        migrations.RemoveField(
            model_name='history',
            name='type',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
